name: twitter_clone
description: Full Stack Twitter App building with Appwrite - Works on Android & iOS!
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  any_link_preview: ^3.0.0
  appwrite: ^9.0.0
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  fpdart: ^0.4.0
  image_picker: ^0.8.6+1
  like_button: ^2.0.5
  shimmer: ^2.0.0
  timeago: ^3.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
